%YAML 1.3
---
- Key: [Back Button, pressed]
- KeyPress: Escape
...
---
- Key: [Forward Button, pressed]
- KeyPress: Return
...
---
- Key: [Button 6, pressed]
- KeyPress: Up
...
---
- Key: [Left Scroll As Button 7, pressed]
- KeyPress: Down
...
